#!/usr/bin/env ruby
require './lib/auto_grader'
require 'optparse'
load 'lib/graders/manual_grader.rb'

options = {}
o = nil
OptionParser.new do |opts|
  o = opts
  opts.banner = "Usage: #{$0} [options] input"
  #opts.on('-a', '--app PATH', 'Path to app') {|p| options[:app] = p}
  opts.on('-h', '--help', 'Display this screen') { puts opts; exit }
end.parse!

#unless options[:app] and ARGV.count == 2
unless ARGV.count == 1
  puts o
  exit 1
end

d = Dir::getwd

begin
  ARGV.collect! {|p| File.expand_path p}

  begin
    g = AutoGrader.create('5', 'ManualGrader', IO.read(ARGV[0]), options)
    g.grade!
  rescue Object => e
    STDERR.puts "*** FATAL: #{e.respond_to?(:message) ? e.message : "unspecified error"}"
    puts e.backtrace
    exit 1
  end
  score_max = 1000
  puts "Score out of #{score_max}: #{g.normalized_score(score_max)}\n"
  puts "---BEGIN grader comments---\n#{'-'*80}\n#{g.comments}\n#{'-'*80}\n---END grader comments---"
ensure
  Dir::chdir d
end
